baseURL: https://utku-odabasi-portfolio.netlify.app/
languageCode: en-us
title: Portfolio Website for Utku Odabasi
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      This is a website where you can view my skills, experiences and hobbies. 
    title: Hi, my name is Utku Odabasi, I'm a student at London Business School
  blog: {}
  contact:
    address:
      - city: London, NW14SA
        country: UK
        street: Regent's Park
        title: Address LBS
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: uodabasi.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 739-239-9822
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Utku Odabasi, London Business School
    enable: yes
    quicklinks:
      - alt: utkuodabasi.com
        text: 'Also visit: '
        url: https://www.utkuodabasi.com/
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/odabasi_utku
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=606847401
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/utku943/
      - icon: fa-github
        label: GitHub
        url: https://github.com/utkuodabasi/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/utku-odabasi/
  image: ''
  name: Utku Odabasi
  navigation:
#    button1:
#      - name: Let's get started
#        url: contents
#    button2:
#     - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About
        url: blogs/about
      - name: My Resume
        url: blogs/cv
      - name: German 2021 Election Poll Study
        url: blogs/US
      - name: Bike Rentals
        url: blogs/bike
      - name: Yields
        url: blogs/yield      
    menu: Menu
    subtitle: More!
    title: Engage
  tiles:
    enable: yes
    showcase:
      - image: pic07.jpg
        subtitle: Learn about me!
        title: About
        url: blogs/about
      - image: cv_default.jpg
        subtitle: See my resume!
        title: Resume
        url: blogs/cv
      - image: election.jpg
        subtitle: German 2021 Election Poll Study
        title: Election prediction
        url: blogs/US
      - image: bike.jpg
        subtitle: A Study about bike rentals
        title: Bike Rentals
        url: blogs/bike
      - image: yield.jpg
        subtitle: A Study about Tresuary Yields
        title: Yields
        url: blogs/yield
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Feel free to contact me. "
    title: Thank you for visiting!
    url: '#'
